import 'package:hive/hive.dart';
import 'sources.dart'; // Ensure this import points to your Sources model

part 'source_response.g.dart'; // This file will be generated by running the builder

@HiveType(typeId: 2) // Ensure typeId is unique
class SourceResponse {
  @HiveField(0)
  final String? status;
  @HiveField(1)
  final String? code;
  @HiveField(2)
  final String? message;
  @HiveField(3)
  final List<Sources>? sources;

  SourceResponse({
    this.status,
    this.code,
    this.message,
    this.sources,
  });

  factory SourceResponse.fromJson(Map<String, dynamic> json) {
    return SourceResponse(
      status: json['status'],
      code: json['code'],
      message: json['message'],
      sources: json['sources'] != null
          ? List<Sources>.from(json['sources'].map((v) => Sources.fromJson(v)))
          : null,
    );
  }
}
