import 'package:hive/hive.dart';

part 'sources.g.dart'; // This file will be generated by running the builder

@HiveType(typeId: 1) // Ensure typeId is unique if you have other Hive objects
class Sources {
  @HiveField(0)
  final String? id;
  @HiveField(1)
  final String? name;
  @HiveField(2)
  final String? description;
  @HiveField(3)
  final String? url;
  @HiveField(4)
  final String? category;
  @HiveField(5)
  final String? language;
  @HiveField(6)
  final String? country;

  Sources({
    this.id,
    this.name,
    this.description,
    this.url,
    this.category,
    this.language,
    this.country,
  });

  factory Sources.fromJson(Map<String, dynamic> json) {
    return Sources(
      id: json['id'],
      name: json['name'],
      description: json['description'],
      url: json['url'],
      category: json['category'],
      language: json['language'],
      country: json['country'],
    );
  }
}
